### ISSUE TITLE
Any way to port for Xamarin Forms/MUAI?

### ISSUE THREAD

**Issue by Arslan007** [prahladyeri/sqlite-gui#2]
Any easy way to port for Xamarn Form/MUAI

**Comment by prahladyeri** [comment]
I don't know much about those UX frameworks (Xamarin Forms and .NET MAUI). Below are a few links which might be helpful in conversion:

- https://www.syncfusion.com/blogs/post/guest-blog-from-winforms-to-xamarin-one-developer-s-journey.aspx
- https://learn.microsoft.com/en-us/answers/questions/683367/migrate-from-winforms-to-net-maui.html
- https://learn.microsoft.com/en-us/answers/questions/295634/from-winforms-to-xamarin-maui-for-windows-mac-linu.html
- https://stackoverflow.com/questions/40251492/how-to-translate-windows-form-app-to-work-in-xamarin
